/* Generated by Yosys 0.60+70 (git sha1 8101c87fa, clang++ 18.1.8 -fPIC -O3) */

module LUT3_GHPC(I0, I1, I2, clk, r, O);
  input [1:0] I0;
  wire [1:0] I0;
  input [1:0] I1;
  wire [1:0] I1;
  input [1:0] I2;
  wire [1:0] I2;
  input clk;
  wire clk;
  input [7:0] r;
  wire [7:0] r;
  output [1:0] O;
  wire [1:0] O;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire [2:0] _019_;
  wire [2:0] _020_;
  wire [2:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire [7:0] _025_;
  wire _026_;
  wire [7:0] _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire [2:0] _068_;
  wire [23:0] _069_;
  wire [7:0] _070_;
  wire [7:0] _071_;
  wire [7:0] _072_;
  wire [7:0] _073_;
  wire _074_;
  wire [2:0] _075_;
  wire _076_;
  wire [7:0] _077_;
  wire [2:0] _078_;
  wire [2:0] _079_;
  wire [0:0] _080_;
  wire [0:0] _081_;
  wire _082_;
  wire _083_;
  \$bmux  #(
    .S_WIDTH(32'd3),
    .WIDTH(32'd1)
  ) _085_ (
    .A(r),
    .S({ I2[1], I1[1], I0[1] }),
    .Y(_015_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _087_ (
    .CLK(clk),
    .D(I0[1]),
    .Q(_001_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _089_ (
    .CLK(clk),
    .D(I1[1]),
    .Q(_006_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _091_ (
    .CLK(clk),
    .D(I2[1]),
    .Q(_011_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _093_ (
    .CLK(clk),
    .D(_015_),
    .Q(_016_)
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _095_ (
    .A(I0[0]),
    .B(I1[0]),
    .Y(_027_[7])
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _096_ (
    .A(_069_[6]),
    .B(I1[0]),
    .Y(_027_[6])
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _097_ (
    .A(I1[0]),
    .Y(_069_[4])
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _098_ (
    .A(I0[0]),
    .B(_069_[4]),
    .Y(_027_[5])
  );
  \$not  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _099_ (
    .A(I0[0]),
    .Y(_069_[6])
  );
  \$and  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _100_ (
    .A(_069_[6]),
    .B(_069_[4]),
    .Y(_027_[4])
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _101_ (
    .A(r[0]),
    .B(_027_[7]),
    .Y(_029_)
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _102_ (
    .A(r[1]),
    .B(_027_[6]),
    .Y(_034_)
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _103_ (
    .A(r[2]),
    .B(_027_[5]),
    .Y(_039_)
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _104_ (
    .A(r[3]),
    .B(_027_[4]),
    .Y(_044_)
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _105_ (
    .A(r[4]),
    .B(_027_[7]),
    .Y(_049_)
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _106_ (
    .A(r[5]),
    .B(_027_[6]),
    .Y(_054_)
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _107_ (
    .A(r[6]),
    .B(_027_[5]),
    .Y(_059_)
  );
  \$xor  #(
    .A_SIGNED(32'd0),
    .A_WIDTH(32'd1),
    .B_SIGNED(32'd0),
    .B_WIDTH(32'd1),
    .Y_WIDTH(32'd1)
  ) _108_ (
    .A(r[7]),
    .B(_027_[4]),
    .Y(_064_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _110_ (
    .CLK(clk),
    .D(_029_),
    .Q(_030_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _112_ (
    .CLK(clk),
    .D(_034_),
    .Q(_035_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _114_ (
    .CLK(clk),
    .D(_039_),
    .Q(_040_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _116_ (
    .CLK(clk),
    .D(_044_),
    .Q(_045_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _118_ (
    .CLK(clk),
    .D(_049_),
    .Q(_050_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _120_ (
    .CLK(clk),
    .D(_054_),
    .Q(_055_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _122_ (
    .CLK(clk),
    .D(_059_),
    .Q(_060_)
  );
  \$dff  #(
    .CLK_POLARITY(32'd1),
    .WIDTH(32'd1)
  ) _124_ (
    .CLK(clk),
    .D(_064_),
    .Q(_065_)
  );
  \$bmux  #(
    .S_WIDTH(32'd3),
    .WIDTH(32'd1)
  ) _126_ (
    .A({ _065_, _060_, _055_, _050_, _045_, _040_, _035_, _030_ }),
    .S({ _011_, _006_, _001_ }),
    .Y(_076_)
  );
  assign _073_ = { _065_, _060_, _055_, _050_, _045_, _040_, _035_, _030_ };
  assign _025_ = r;
  assign _024_ = _076_;
  assign _023_ = _015_;
  assign _022_ = _016_;
  assign _021_ = { _011_, _006_, _001_ };
  assign _020_ = { I2[1], I1[1], I0[1] };
  assign _019_ = { I2[0], I1[0], I0[0] };
  assign _082_ = clk;
  assign _074_ = clk;
  assign _075_ = { _011_, _006_, _001_ };
  assign _077_ = { _065_, _060_, _055_, _050_, _045_, _040_, _035_, _030_ };
  assign _032_ = _029_;
  assign _031_ = _030_;
  assign _028_ = clk;
  assign _037_ = _034_;
  assign _036_ = _035_;
  assign _033_ = clk;
  assign _042_ = _039_;
  assign _041_ = _040_;
  assign _038_ = clk;
  assign _047_ = _044_;
  assign _046_ = _045_;
  assign _043_ = clk;
  assign _052_ = _049_;
  assign _051_ = _050_;
  assign _048_ = clk;
  assign _057_ = _054_;
  assign _056_ = _055_;
  assign _053_ = clk;
  assign _062_ = _059_;
  assign _061_ = _060_;
  assign _058_ = clk;
  assign _067_ = _064_;
  assign _066_ = _065_;
  assign _063_ = clk;
  assign _026_ = clk;
  assign _027_[3:0] = _027_[7:4];
  assign _068_ = { I2[0], I1[0], I0[0] };
  assign { _069_[23:12], _069_[10:7], _069_[5], _069_[3:0] } = { I2[0], I1[0], I0[0], I2[0], I1[0], _069_[6], I2[0], _069_[4], I0[0], I2[0], _069_[4], _069_[6], I1[0], I0[0], _069_[11], I1[0], _069_[11], I0[0], _069_[11], _069_[4], _069_[6] };
  assign _070_ = r;
  assign _071_ = { _064_, _059_, _054_, _049_, _044_, _039_, _034_, _029_ };
  assign _072_ = { _065_, _060_, _055_, _050_, _045_, _040_, _035_, _030_ };
  assign _014_ = clk;
  assign _017_ = _016_;
  assign _018_ = _015_;
  assign _009_ = clk;
  assign _010_ = I2[1];
  assign _012_ = _011_;
  assign _013_ = I2[1];
  assign _004_ = clk;
  assign _005_ = I1[1];
  assign _007_ = _006_;
  assign _008_ = I1[1];
  assign _083_ = clk;
  assign _000_ = I0[1];
  assign _002_ = _001_;
  assign _003_ = I0[1];
  assign O = { _076_, _016_ };
  assign _078_ = { I2[0], I1[0], I0[0] };
  assign _079_ = { I2[1], I1[1], I0[1] };
  assign _080_ = _016_;
  assign _081_ = _076_;
endmodule
