/* Generated by Yosys 0.60+70 (git sha1 8101c87fa, clang++ 18.1.8 -fPIC -O3) */

module GHPC_Gadget(in0, in1, r, clk, out0, out1);
  input [2:0] in0;
  wire [2:0] in0;
  input [2:0] in1;
  wire [2:0] in1;
  input [7:0] r;
  wire [7:0] r;
  input clk;
  wire clk;
  output out0;
  wire out0;
  output out1;
  wire out1;
  wire [3:0] _0_;
  wire [1:0] _1_;
  wire _2_;
  wire [2:0] in1_reg;
  wire out0_mid;
  wire [7:0] step1_reg;
  assign _0_[0] = in1[0] ? r[1] : r[0];
  assign _0_[1] = in1[0] ? r[3] : r[2];
  assign _0_[2] = in1[0] ? r[5] : r[4];
  assign _0_[3] = in1[0] ? r[7] : r[6];
  assign _1_[0] = in1[1] ? _0_[1] : _0_[0];
  assign _1_[1] = in1[1] ? _0_[3] : _0_[2];
  assign _2_ = in1[2] ? _1_[1] : _1_[0];
  reg_Bbehavioral \gen_in:1.reg_ins1  (
    .clk(clk),
    .d(in1[0]),
    .q(in1_reg[0])
  );
  reg_Bbehavioral \gen_in:2.reg_ins1  (
    .clk(clk),
    .d(in1[1]),
    .q(in1_reg[1])
  );
  reg_Bbehavioral \gen_in:3.reg_ins1  (
    .clk(clk),
    .d(in1[2]),
    .q(in1_reg[2])
  );
  reg_Bbehavioral \gen_out:1.gen_ll.reg_out0_ins2  (
    .clk(clk),
    .d(out0_mid),
    .q(out0)
  );
  ghpc_step1_Bbehavioral_3_1_8_1_1 step1_ins (
    .clk(clk),
    .in0(in0),
    .r(r),
    .step1_reg(step1_reg)
  );
  ghpc_step2_Bbehavioral_3_1_1_1 step2_inst (
    .clk(clk),
    .\input (in1_reg),
    .\output (out1),
    .step1_reg(step1_reg)
  );
  assign out0_mid = _2_;
endmodule

module ghpc_step1_Bbehavioral_3_1_8_1_1(in0, r, clk, step1_reg);
  input [2:0] in0;
  wire [2:0] in0;
  input [7:0] r;
  wire [7:0] r;
  input clk;
  wire clk;
  output [7:0] step1_reg;
  wire [7:0] step1_reg;
  wire [7:0] funcout;
  wire [23:0] in0_comb;
  wire [7:0] step1;
  assign funcout[7] = in0[0] & in0[1];
  assign funcout[6] = in0_comb[6] & in0[1];
  assign in0_comb[4] = ~ in0[1];
  assign funcout[5] = in0[0] & in0_comb[4];
  assign in0_comb[6] = ~ in0[0];
  assign funcout[4] = in0_comb[6] & in0_comb[4];
  assign step1[0] = r[0] ^ funcout[7];
  assign step1[1] = r[1] ^ funcout[6];
  assign step1[2] = r[2] ^ funcout[5];
  assign step1[3] = r[3] ^ funcout[4];
  assign step1[4] = r[4] ^ funcout[7];
  assign step1[5] = r[5] ^ funcout[6];
  assign step1[6] = r[6] ^ funcout[5];
  assign step1[7] = r[7] ^ funcout[4];
  reg_Bbehavioral \gen_out:1.gen_step1_1:1.reg_ins  (
    .clk(clk),
    .d(step1[0]),
    .q(step1_reg[0])
  );
  reg_Bbehavioral \gen_out:1.gen_step1_1:2.reg_ins  (
    .clk(clk),
    .d(step1[1]),
    .q(step1_reg[1])
  );
  reg_Bbehavioral \gen_out:1.gen_step1_1:3.reg_ins  (
    .clk(clk),
    .d(step1[2]),
    .q(step1_reg[2])
  );
  reg_Bbehavioral \gen_out:1.gen_step1_1:4.reg_ins  (
    .clk(clk),
    .d(step1[3]),
    .q(step1_reg[3])
  );
  reg_Bbehavioral \gen_out:1.gen_step1_1:5.reg_ins  (
    .clk(clk),
    .d(step1[4]),
    .q(step1_reg[4])
  );
  reg_Bbehavioral \gen_out:1.gen_step1_1:6.reg_ins  (
    .clk(clk),
    .d(step1[5]),
    .q(step1_reg[5])
  );
  reg_Bbehavioral \gen_out:1.gen_step1_1:7.reg_ins  (
    .clk(clk),
    .d(step1[6]),
    .q(step1_reg[6])
  );
  reg_Bbehavioral \gen_out:1.gen_step1_1:8.reg_ins  (
    .clk(clk),
    .d(step1[7]),
    .q(step1_reg[7])
  );
  assign funcout[3:0] = funcout[7:4];
  assign { in0_comb[23:12], in0_comb[10:7], in0_comb[5], in0_comb[3:0] } = { in0, in0[2:1], in0_comb[6], in0[2], in0_comb[4], in0[0], in0[2], in0_comb[4], in0_comb[6], in0[1:0], in0_comb[11], in0[1], in0_comb[11], in0[0], in0_comb[11], in0_comb[4], in0_comb[6] };
endmodule

module ghpc_step2_Bbehavioral_3_1_1_1(step1_reg, \input , clk, \output );
  input [7:0] step1_reg;
  wire [7:0] step1_reg;
  input [2:0] \input ;
  wire [2:0] \input ;
  input clk;
  wire clk;
  output \output ;
  wire \output ;
  wire _0_;
  wire [3:0] _1_;
  wire [1:0] _2_;
  assign _2_[1] = \input [1] ? _1_[3] : _1_[2];
  assign _0_ = \input [2] ? _2_[1] : _2_[0];
  assign _1_[0] = \input [0] ? step1_reg[1] : step1_reg[0];
  assign _1_[1] = \input [0] ? step1_reg[3] : step1_reg[2];
  assign _1_[2] = \input [0] ? step1_reg[5] : step1_reg[4];
  assign _1_[3] = \input [0] ? step1_reg[7] : step1_reg[6];
  assign _2_[0] = \input [1] ? _1_[1] : _1_[0];
  assign \output  = _0_;
endmodule

module reg_Bbehavioral(clk, d, q);
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  reg q = 1'h0;
  wire s_current_state;
  wire s_next_state;
  always @(posedge clk)
    q <= d;
  assign s_current_state = q;
  assign s_next_state = d;
endmodule
